"use client";

import { useId, useMemo } from "react";
import { cn } from "./cn";
import { mascotSvg, type MascotState } from "./mascot-svg";

export interface MascotProps {
  state?: MascotState;
  size?: number;
  className?: string;
  /** Accessible label; decorative mascots should pass `decorative`. */
  label?: string;
  decorative?: boolean;
}

/**
 * The Nia walrus. Motion (breathing, blinking, ripples, scan) lives in
 * globals.css and only runs when the user allows motion.
 */
export function Mascot({ state = "idle", size = 120, className, label = "Nia", decorative = false }: MascotProps) {
  const rid = useId().replace(/[^a-zA-Z0-9]/g, "");
  const svg = useMemo(() => mascotSvg({ state, id: `m${rid}`, title: label }), [state, rid, label]);
  return (
    <span
      className={cn("nia-mascot-wrap inline-block shrink-0 select-none", className)}
      style={{ width: size, height: size }}
      data-state={state}
      aria-hidden={decorative || undefined}
      // Static, trusted markup generated by mascotSvg().
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

export type { MascotState };
